#!/bin/bash


# Install dependencies if not installed
for dependency in lolcat figlet
do
	type $dependency > /dev/null

	# $? to check the status of the last command run
	if [ "$?" -ne  0  ]; then  
		sudo apt-get -y install $dependency
	fi
done


echo 'Servers reports' | figlet | lolcat


# finds hosts in .ssh/config file
hosts=$(cat ~/.ssh/config | grep -Po "^Host (.*)" | awk '{print $2}')

for h in $hosts; do
	echo "Getting infos from : " + $h | lolcat
	ssh $h <<-EOF>> report
	echo "Starting report for : ${h}"
		uname -a

		df -h 
		uptime
		free -mh
		lscpu | grep -E "^CPU(s)"
	echo "Ending report for : ${h}"
	EOF
done

echo "Reports done !"
