#!/bin/bash

# Install dependencies if not installed
for dependency in lolcat figlet
do
	type $dependency > /dev/null

	# $? to check the status of the last command run
	if [ "$?" -ne  0  ]; then  
		sudo apt-get -y install $dependency
	fi
done


echo 'Servers reports' | figlet | lolcat


# finds hosts in .ssh/config file
hosts=$(cat ~/.ssh/config | grep -Po "^Host (.*)" | awk '{print $2}')

for h in $hosts; do
	printf '\n' {1..5}
	echo "Getting infos from : "  $h | lolcat
	ssh $h <<-EOF
	echo -e "Starting report for : \e[1m\e[42m${h}\e[0m"
	    echo -e "\e[96mDistribution :\e[0m"
		uname -a

		echo -e "\e[96mDisk usage : \e[0m"
		df -h

		echo -e "\e[96mUptime : \e[0m"
		uptime

		echo -e "\e[96mMemory : \e[0m"
		free -mh

		echo -e "\e[96mNumber of cpus : \e[0m"
		lscpu | grep -E "^CPU\(s\)": | awk '{print $2}'
	echo "Ending report for : ${h}"
	EOF
done



echo "Reports done !"
